version: '3'
services:
  php-apache:
    image: teste-php
    ports:
      - "8080:80" # Mapeie a porta 8080 do host para a porta 80 do container
    volumes:
      - ./:/var/www/html # Mapeie o diretório do seu projeto para o diretório do Apache
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: teste-php-db
